### ISSUE TITLE
Error: KeyError: 'total_results'

### ISSUE THREAD

**Issue by webkaiyo** [ratsclub/nuke#2]
This error occurs when `nuke` is initialized.

Usage: `py main.py --token my_token_here --log log.txt`

Traceback:
```
Traceback (most recent call last):
  File "main.py", line 256, in <module>
    asyncio.run(main())
  File "...\Python\Python38-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "...\Python\Python38-32\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "main.py", line 223, in main
    result = await search_messages(session, chat, user)
  File "main.py", line 89, in search_messages
    total_results = result["total_results"]
KeyError: 'total_results'
```

I don't know exactly what is the error cause, that's why I'm creating an issue instead creating a PR.

**Comment by ratsclub** [comment]
It seems that the ``/api/guild/{?}/messages/search`` endpoint isn't returning this field some times. I'll check it out and write a patch to fix it.

**Comment by webkaiyo** [comment]
Hey, @ratsclub. Thank you for the fast answer.

There is currently nothing registered in the [Discord's documentation changelog](https://discord.com/developers/docs/change-log), which *may* suggest that it is an internal change to the API. Discord has the attitude of not documenting changes or documenting in the last minute. The only solution I see for this problem is to remove this variable from all the code (since Discord is no longer providing this information, apparently).

**Comment by webkaiyo** [comment]
Hey, @ratsclub. Thank you for the fast answer. Could this be considered a bug by Discord itself? It makes no sense to me to provide this information only a few times.

**Comment by ratsclub** [comment]
As far as I can tell the whole endpoint is not documented and it seems they aren't planning to do it so.

**Comment by ratsclub** [comment]
@webkaiyo I've made a patch  that should fix your issues. Feel free to test it and report the results as I'll be glad to help you.

**Comment by webkaiyo** [comment]
Hoi, @ratsclub. Thank you for the fast update. I'll surely test your new patch, thanks again for the dedication.
